version: '3.4'

volumes:
    news2:    

services:
    newsappdb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Password123
        ports:
            - 1433:1433
        volumes:
            - news2:/var/opt/mssql

    newsappnet:
        image: ${DOCKER_REGISTRY-}newsappnet
        container_name: sampleBack
        build:
            context: .
            dockerfile: NewsAppNet/Dockerfile
        depends_on:
            - newsappdb
        ports:
            - 5000:80

    newsapp-redux:
        image: ${DOCKER_REGISTRY-}newsapp-redux
        container_name: sampleFront
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true