version: '3.4'

volumes:
    news2:    

services:
    newsappdb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Password123
        ports:
            - 1436:1436
        volumes:
            - news2:/var/opt/mssql

    newsappnet:
        image: ${DOCKER_REGISTRY-}newsappnet
        build:
            context: .
            dockerfile: NewsAppNet/Dockerfile
        depends_on:
            - newsappdb
        ports:
            - 5000:80

