version: '3.4'

volumes:
    news5:    

services:
    newsappdb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Password123
        ports:
            - 1433:1433
        volumes:
            - news5:/var/opt/mssql

    newsappnet:
        image: newsappnet:latest
        build:
            context: .
            dockerfile: NewsAppNet/Dockerfile
        depends_on:
            - newsappdb
        ports:
            - 5000:80

    frontend:
        image: newsapp-redux
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_BACKEND_PORT=5000